version: 2
formats:
  - epub
  - htmlzip
  - pdf
sphinx:
  configuration: source/conf.py

build:
  os: 'ubuntu-24.04'
  tools:
    python: '3.13'
  apt_packages:
    - texlive-latex-extra
    - texlive-fonts-recommended
    - latexmk

python:
  install:
  - requirements: requirements.txt
